# Generated by Django 3.2.8 on 2021-10-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=500)),
                ('Btn', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery_acid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
