# Generated by Django 3.2.8 on 2021-10-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0002_author_category_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
