# Generated by Django 3.2.8 on 2021-11-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0007_auto_20211105_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_acid',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='jungleapp.gallery_acid'),
        ),
        migrations.AddField(
            model_name='gallery_acid',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='jungleapp.gallery_acid'),
        ),
    ]
