# Generated by Django 3.2.8 on 2021-11-14 18:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0013_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='crags',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crags',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crags',
            name='gallery_btn',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crags',
            name='overview',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gallery_acid',
            name='crag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jungleapp.crags'),
        ),
    ]
