# Generated by Django 3.2.8 on 2021-11-15 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0015_commentcrag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcrag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentscrag', to='jungleapp.crags'),
        ),
    ]
