# Generated by Django 3.2.8 on 2021-11-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0018_dificulty_routes_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
