# Generated by Django 3.2.8 on 2021-11-17 01:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0020_auto_20211116_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectors',
            name='guidebook',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
