# Generated by Django 3.2.8 on 2021-11-17 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0022_auto_20211116_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_of_climb',
            old_name='grades',
            new_name='type',
        ),
    ]
