# Generated by Django 3.2.8 on 2021-11-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0023_rename_grades_type_of_climb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_of_climb',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
