# Generated by Django 3.2.8 on 2021-11-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0024_alter_type_of_climb_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectors',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
