# Generated by Django 3.2.8 on 2021-11-17 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0025_sectors_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='dificulty',
        ),
        migrations.AddField(
            model_name='sectors',
            name='dificulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jungleapp.dificulty'),
        ),
    ]
