# Generated by Django 3.2.8 on 2021-11-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0026_auto_20211116_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='crag',
        ),
    ]
