# Generated by Django 3.2.8 on 2021-11-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0027_remove_routes_crag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='type_of_climb',
        ),
    ]
