# Generated by Django 3.2.8 on 2021-11-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0031_alter_commentroute_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectors',
            name='route_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
