# Generated by Django 3.2.8 on 2023-10-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0035_auto_20211128_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='crags',
            name='Btn_sector',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
