# Generated by Django 3.2.8 on 2023-10-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungleapp', '0036_auto_20231005_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
